name: learnecke-new-design-frontend-container

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/learnecke-new-design.yaml"
      - "Dockerfile"

env:
  ECR_REGION: us-east-1
  ECR_IMG: learnecke/frontend-v2

jobs:
  learnecke-new-design-frontend-container:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Create ECR Repo if not Exists
        uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: ${{ env.ECR_IMG }}
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.ecr.outputs.repository-uri }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      